//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DBEntities : DbContext
{
    public DBEntities()
        : base("name=DBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Banner> Banners { get; set; }
    public DbSet<ChuyenDe> ChuyenDes { get; set; }
    public DbSet<HinhAnhHoatDong> HinhAnhHoatDongs { get; set; }
    public DbSet<LienKetHuuIch> LienKetHuuIches { get; set; }
    public DbSet<Menu> Menus { get; set; }
    public DbSet<NguoiDung> NguoiDungs { get; set; }
    public DbSet<TabThongTin> TabThongTins { get; set; }
    public DbSet<ThongBao> ThongBaos { get; set; }
    public DbSet<ThongTinWebSite> ThongTinWebSites { get; set; }
    public DbSet<TinBai> TinBais { get; set; }
    public DbSet<VanBan> VanBans { get; set; }
    public DbSet<Video> Videos { get; set; }
}
